# config/models.yaml
models:
  qwen:
    api_url: "https://api.qwen.ai/v1/chat/completions"
    api_key: "${QWEN_API_KEY}"
    model_name: "qwen-turbo"
    max_tokens: 4000
    temperature: 0.7
    timeout: 45
    retry_attempts: 3
    retry_delay: 2
    rate_limit: 100
    
  deepseek:
    api_url: "https://api.deepseek.com/v1/chat/completions"
    api_key: "${DEEPSEEK_API_KEY}"
    model_name: "deepseek-chat"
    max_tokens: 4000
    temperature: 0.7
    timeout: 30
    retry_attempts: 3
    retry_delay: 1
    rate_limit: 100
    
  gpt4o:
    api_url: "https://api.openai.com/v1/chat/completions"
    api_key: "${GPT4O_API_KEY}"
    model_name: "gpt-4o"
    max_tokens: 4000
    temperature: 0.7
    timeout: 60
    retry_attempts: 3
    retry_delay: 3
    rate_limit: 100 