# config/models.yaml
models:
  qwen:
    api_url: "https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation"
    api_key: "${QWEN_API_KEY}"
    model_name: "qwen-plus"
    max_tokens: 16000
    temperature: 0.7
    timeout: 45
    retry_attempts: 3
    retry_delay: 2
    rate_limit: 100
    
  # Qwen Fallback Model (Alibaba Cloud) - for agent fallback
  qwen_fallback:
    api_url: "https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation"
    api_key: "${QWEN_API_KEY}"
    model_name: "qwen3-235b-a22b"
    max_tokens: 16000
    temperature: 0.7
    timeout: 45
    retry_attempts: 3
    retry_delay: 2
    rate_limit: 100
    
  deepseek:
    api_url: "https://api.deepseek.com/v1/chat/completions"
    api_key: "${DEEPSEEK_API_KEY}"
    model_name: "deepseek-reasoner"
    max_tokens: 32000
    temperature: 0.7
    timeout: 30
    retry_attempts: 3
    retry_delay: 1
    rate_limit: 100
    
  # Personal ChatGPT Server (Primary - for China users)
  personal_chatgpt:
    api_url: "${PERSONAL_CHATGPT_URL}"
    api_key: "${PERSONAL_CHATGPT_API_KEY}"
    model_name: "gpt-4o"
    max_tokens: 32000
    temperature: 0.7
    timeout: 60
    retry_attempts: 3
    retry_delay: 3
    rate_limit: 100
    
  # OpenAI GPT-4o API Configuration (Removed - using Personal ChatGPT Server only)
  # gpt4o:
  #   api_url: "https://api.openai.com/v1/chat/completions"
  #   api_key: "${GPT4O_API_KEY}"
  #   model_name: "gpt-4o"
  #   max_tokens: 32000
  #   temperature: 0.7
  #   timeout: 60
  #   retry_attempts: 3
  #   retry_delay: 3
  #   rate_limit: 100 